---
title: "Ciprofloxacin AMR Prediction"
author: "Arvon Clemons, Mark Vater"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r warning = FALSE, message=FALSE, echo=FALSE}
#install packages only if you have not already done so 
list.of.packages <- c("randomForest", "ggplot2", "dplyr", "caret",
                      "readr", "e1071", "mlbench", "slam","parallel", "doParallel")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
#library packages
for (pkg in c("randomForest", "ggplot2", "dplyr",
              "caret", "readr","parallel", "doParallel")) {
  library(pkg, character.only = TRUE)
  }
```

# Import and Split Data
```{r}
#Import
## May require using "data_clean_script.R" to create "unitigs_cip.csv" in local directory
cipData <- read_csv("./unitigs_cip.csv", col_types = cols(.default = col_factor(NULL))) %>% 
  select_if(sapply(., nlevels) > 1)
#Split
set.seed(05101929)
index <- cipData$cip_sr %>% 
  createDataPartition(times = 1, p = 0.7, list = FALSE)

cipTrain <- cipData %>% slice(index)
cipTest <- cipData %>% slice(-index)

```

# Practice Model Training and Fit
```{r}
miniData <- cipData[1:1200, ]
index2 <- miniData$cip_sr %>% 
  createDataPartition(times = 1, p = 0.8, list = FALSE)

miniTrain <- miniData %>% slice(index2)
miniTest <- miniData %>% slice(-index2)

trCtrl <- trainControl("cv", number = 10,
                       allowParallel = TRUE) #cross-validation

cl <- makePSOCKcluster(6)
registerDoParallel(cl)
set.seed(05101929)

system.time(
  pracRF <- train(
    cip_sr~., data=miniTrain, method="parRF",
    trControl = trCtrl,
    importance = T
  )
)
stopCluster(cl)


saveRDS(pracRF, file = "mockRF_model") #save practice model
predictedAR <- pracRF %>% predict(miniTest) #predictions
mean(predictedAR == miniTest$cip_sr) #assess model accuracy
#[1] 0.9707113
```

# Full Model Training and Fit (DO NOT RUN!!!!)
```{r}
trCtrl <- trainControl("cv", number = 10) #cross-validation

# Select Cores for Parallelization
cl <- makePSOCKcluster(8)
registerDoParallel(cl)
set.seed(05101929)

# #Model Fit
# system.time(
# modelRF <- train(
#   cip_sr ~., data = cipTrain, method = "rf",
#   trControl = trCtrl,
#   importance = TRUE
#   )
# )
# After fitting model
stopCluster(cl)

# Best tuning parameter
model$bestTune
```
